da = read.table("d-gmsp9908.txt", header = TRUE)
head(da)
gm=log(da[,2]+1)
Box.test(gm,lag = 10, type = 'Ljung')
Box.test((gm-mean(gm))^2,lag = 10, type = 'Ljung')
pacf((gm-mean(gm))^2,lag=10)
m1=garchFit(~arma(2,0)+garch(1,1),data=gm,trace = F)
summary(m1)
m2=garchFit(~garch(1,1),data=gm,trace = F)
summary(m2)
m3=garchFit(~garch(1,1),data=gm,cond.dist = "ged",trace = F)
summary(m3)
sp=log(da[,3]+1)
Box.test(sp,lag = 10, type = 'Ljung')
Box.test((sp-mean(sp))^2,lag = 10, type = 'Ljung')
acf(sp)
pacf(sp)
m4=garchFit(~arma(2,0)+garch(1,1),data=sp,con.dist='std',trace = F)
summary(m4)
source("garchM.R")
m5=garchM(gm)
source("Egarch.R")
m6=Egarch(gm)
sp1=sp*100
gm1=gm*100
m7=garchFit(~arma(5,0)+garch(1,1),data=sp1,cond.dist = "ged",trace = F)
summary(m7)