require(xts)
require(fGarch)
da = read.table("m-3m4608.txt", header = T)
head(da)
dim(da)
rtn=as.numeric(as.character(da[2:756,2]))
intc=log(rtn+1)
at=intc-mean(intc)
Box.test(intc,lag=12,type='Ljung')
Box.test(intc,lag=6,type='Ljung')
Box.test(at^2,lag=12,type='Ljung')
pacf(at^2)
m1 = garchFit(~ garch(2, 0), data = intc, trace = F)
summary(m1)
intc2=intc[1:750]
m2 = garchFit(~ garch(2, 0), data = intc2, trace = F)
summary(m2)
predict(m2, 5)
source("garchM.R")
m3=garchM(intc)
source("Egarch.R")
m4=Egarch(intc)