require(xts)
require(fGarch)
da = read.table("m-gmsp5008.txt", header = T)
lgm=log(da[,2]+1)*100
acf(lgm)
m1 = garchFit(~ garch(1, 1), data = lgm, trace = F)
summary(m1)
source("garchM.R")
m2=garchM(lgm)
m3 = garchFit(~ garch(1, 1), data = lgm, cond.dist = 'std', trace = F)
summary(m3)
source("Egarch.R")
m4=Egarch(lgm)
predict(m1,6)
predict(m3,6)
rt=lgm/100
m5=Tgarch11(rt)
sp=log(da[,3]+1)
pacf((sp-mean(sp))^2)
m6=garchFit(~ garch(1, 1), data = sp, trace = F)
summary(m6)